In [24]:
import numpy as np

In [25]:
import pandas as pd

master = pd.read_excel('AR6 Country Database.xlsx')

master.head()

,Model,Scenario,Region,Variable,Unit,1990,1995,2000,2005,2007,2008,2010,2011,2012,2013,2014,2015,2018,2020,2021,2022,2023,2024,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100,2110,2130,2150
0,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Carbon Sequestration|CCS|Fossil,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Consumption,billion US$2010/yr,NaN,NaN,NaN,NaN,NaN,NaN,1938.938790,NaN,NaN,NaN,NaN,2050.443979,NaN,2283.981465,NaN,NaN,NaN,NaN,2589.256395,2919.127020,3254.001592,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,473.103455,NaN,NaN,NaN,NaN,446.043213,NaN,416.863159,NaN,NaN,NaN,NaN,396.592651,412.047394,433.487579,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,321.993973,NaN,NaN,NaN,NaN,307.740860,NaN,309.829834,NaN,NaN,NaN,NaN,319.038116,331.080795,344.977493,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Commercial,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,19.644783,NaN,NaN,NaN,NaN,20.231993,NaN,22.672163,NaN,NaN,NaN,NaN,25.879625,29.244556,32.631683,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1034655 entries, 0 to 1034654
Data columns (total 42 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   Model     1034655 non-null  object
 1   Scenario  1034655 non-null  object
 2   Region    1034655 non-null  object
 3   Variable  1034655 non-null  object
 4   Unit      1034655 non-null  object
 5   1990      0 non-null        float64
 6   1995      0 non-null        float64
 7   2000      0 non-null        float64
 8   2005      351502 non-null   float64
 9   2007      0 non-null        float64
 10  2008      0 non-null        float64
 11  2010      756050 non-null   float64
 12  2011      16320 non-null    float64
 13  2012      222 non-null      float64
 14  2013      0 non-null        float64
 15  2014      10446 non-null    float64
 16  2015      1004620 non-null  float64
 17  2018      2660 non-null     float64
 18  2020      1013043 non-null  float64
 19  2021      0 non-null        float64
 20  2022      0 non-null        float64
 21  2023      0 non-null        float64
 22  2024      0 non-null        float64
 23  2025      1010760 non-null  float64
 24  2030      1027902 non-null  float64
 25  2035      983824 non-null   float64
 26  2040      987190 non-null   float64
 27  2045      981979 non-null   float64
 28  2050      986276 non-null   float64
 29  2055      508452 non-null   float64
 30  2060      781624 non-null   float64
 31  2065      501966 non-null   float64
 32  2070      777485 non-null   float64
 33  2075      501589 non-null   float64
 34  2080      775839 non-null   float64
 35  2085      466751 non-null   float64
 36  2090      742274 non-null   float64
 37  2095      466430 non-null   float64
 38  2100      741039 non-null   float64
 39  2110      0 non-null        float64
 40  2130      0 non-null        float64
 41  2150      0 non-null        float64
dtypes: float64(37), object(5)
memory usage: 331.5+ MB

In [27]:
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)  # Display all rows
print(master['Region'].value_counts())

Region
JPN    103951
CHN     96484
BRA     93547
IND     91983
USA     88977
CAN     71998
RUS     71942
EU      69993
KOR     61333
ZAF     49287
IDN     33297
MEX     32272
ARG     22721
TUR     21503
THA     12377
VNM     11887
AUS     11801
COL     10874
SAU     10714
PAK     10666
TWN      9715
GBR      2615
DEU      1739
FRA      1712
SWE      1703
ESP      1689
POL      1679
GRC      1655
CZE      1634
FIN      1632
ITA      1599
CHE       950
NGA       936
UGA       936
PER       936
NZL       936
MOZ       936
BGD       936
BOL       936
CHL       936
EGY       936
ETH       936
GHA       936
KEN       936
VEN       936
ROU       756
HUN       751
NLD       750
SVN       729
IRL       722
DNK       715
PRT       711
BEL       710
SVK       709
BGR       706
HRV       702
LTU       681
AUT       681
LVA       678
NOR       664
EST       658
LUX       647
MYS       592
ECU       417
MLT       113
CYP       113
ISL        53
NIC        25
PNG        25
NPL        25
OMN        25
PAN        25
PHL        25
PSE        25
PRI        25
PRK        25
PRY        25
PYF        25
QAT        25
NCL        25
NER        25
MKD        25
NAM        25
MYT        25
MWI        25
MUS        25
MTQ        25
MRT        25
MNG        25
MNE        25
MMR        25
MLI        25
MDV        25
MDG        25
MDA        25
MAR        25
MAC        25
REU        25
SUR        25
RWA        25
TLS        25
LKA        25
ZMB        25
YEM        25
WSM        25
VUT        25
VIR        25
VCT        25
UZB        25
URY        25
UKR        25
TZA        25
TUN        25
TTO        25
TON        25
TKM        25
SDN        25
TJK        25
TGO        25
TCD        25
SYR        25
SYC        25
SWZ        25
STP        25
SRB        25
SOM        25
SLV        25
SLE        25
SLB        25
SGP        25
SEN        25
LSO        25
ERI        25
LCA        25
BLZ        25
DJI        25
CUB        25
CRI        25
CPV        25
COM        25
COG        25
COD        25
CMR        25
CIV        25
CAF        25
BWA        25
BTN        25
BRN        25
BRB        25
BLR        25
LBY        25
BIH        25
BHS        25
BHR        25
BFA        25
BEN        25
BDI        25
AZE        25
ATG        25
ARM        25
ARE        25
ALB        25
AGO        25
AFG        25
ABW        25
DOM        25
DZA        25
ESH        25
FJI        25
LBR        25
LBN        25
LAO        25
KWT        25
KIR        25
KHM        25
KGZ        25
KAZ        25
JOR        25
JAM        25
ISR        25
IRQ        25
IRN        25
HTI        25
HND        25
HKG        25
GUY        25
GUM        25
GUF        25
GTM        25
GRD        25
GNQ        25
GNB        25
GMB        25
GLP        25
GIN        25
GEO        25
GAB        25
FSM        25
ZWE        25
Name: count, dtype: int64

In [28]:
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)  # Display all rows
print(master['Variable'].value_counts().sort_index())

Variable
Agricultural Demand                                                                   1618
Agricultural Demand|Crops                                                              307
Agricultural Demand|Crops|Energy                                                      1230
Agricultural Demand|Crops|Energy|1st generation                                        280
Agricultural Demand|Crops|Energy|2nd generation                                        307
Agricultural Demand|Crops|Feed                                                        1230
Agricultural Demand|Crops|Food                                                         382
Agricultural Demand|Crops|Other                                                       1230
Agricultural Demand|Livestock                                                         1230
Agricultural Demand|Livestock|Food                                                     382
Agricultural Demand|Livestock|Other                                                   1230
Agricultural Production                                                                582
Agricultural Production|Energy                                                         375
Agricultural Production|Energy|Crops                                                   553
Agricultural Production|Energy|Residues                                                184
Agricultural Production|Non-Energy                                                     546
Agricultural Production|Non-Energy|Crops                                               369
Agricultural Production|Non-Energy|Livestock                                           553
Capacity Additions|Electricity|Biomass                                                1434
Capacity Additions|Electricity|Biomass|w/ CCS                                         1312
Capacity Additions|Electricity|Biomass|w/o CCS                                        1424
Capacity Additions|Electricity|Coal                                                   1398
Capacity Additions|Electricity|Coal|w/ CCS                                            1236
Capacity Additions|Electricity|Coal|w/o CCS                                           1391
Capacity Additions|Electricity|Gas                                                    1388
Capacity Additions|Electricity|Gas|w/ CCS                                             1310
Capacity Additions|Electricity|Gas|w/o CCS                                            1373
Capacity Additions|Electricity|Geothermal                                             1003
Capacity Additions|Electricity|Hydro                                                  1356
Capacity Additions|Electricity|Nuclear                                                1356
Capacity Additions|Electricity|Oil                                                    1298
Capacity Additions|Electricity|Oil|w/ CCS                                              487
Capacity Additions|Electricity|Oil|w/o CCS                                            1294
Capacity Additions|Electricity|Solar                                                  1483
Capacity Additions|Electricity|Solar|CSP                                               286
Capacity Additions|Electricity|Solar|PV                                               1467
Capacity Additions|Electricity|Storage Capacity                                         20
Capacity Additions|Electricity|Wind                                                   1483
Capacity Additions|Electricity|Wind|Offshore                                          1010
Capacity Additions|Electricity|Wind|Onshore                                           1460
Capacity|Electricity                                                                  1945
Capacity|Electricity|Biomass                                                          2652
Capacity|Electricity|Biomass|w/ CCS                                                   2457
Capacity|Electricity|Biomass|w/o CCS                                                  2645
Capacity|Electricity|Coal                                                             2626
Capacity|Electricity|Coal|w/ CCS                                                      2457
Capacity|Electricity|Coal|w/o CCS                                                     2628
Capacity|Electricity|Gas                                                              2642
Capacity|Electricity|Gas|w/ CCS                                                       2470
Capacity|Electricity|Gas|w/o CCS                                                      2644
Capacity|Electricity|Geothermal                                                       1761
Capacity|Electricity|Hydro                                                            2637
Capacity|Electricity|Nuclear                                                          2567
Capacity|Electricity|Ocean                                                              10
Capacity|Electricity|Oil                                                              2644
Capacity|Electricity|Oil|w/ CCS                                                        569
Capacity|Electricity|Oil|w/o CCS                                                      1514
Capacity|Electricity|Other                                                             303
Capacity|Electricity|Peak Demand                                                       200
Capacity|Electricity|Solar                                                            2649
Capacity|Electricity|Solar|CSP                                                        1449
Capacity|Electricity|Solar|PV                                                         2632
Capacity|Electricity|Storage                                                           450
Capacity|Electricity|Storage Capacity                                                  432
Capacity|Electricity|Wind                                                             2652
Capacity|Electricity|Wind|Offshore                                                    1762
Capacity|Electricity|Wind|Onshore                                                     2217
Capacity|Hydrogen|Biomass                                                              225
Capacity|Hydrogen|Biomass|w/ CCS                                                       184
Capacity|Hydrogen|Biomass|w/o CCS                                                      225
Capacity|Hydrogen|Coal                                                                 184
Capacity|Hydrogen|Coal|w/ CCS                                                          184
Capacity|Hydrogen|Coal|w/o CCS                                                         184
Capacity|Hydrogen|Electricity                                                          293
Capacity|Hydrogen|Gas                                                                  184
Capacity|Hydrogen|Gas|w/ CCS                                                           184
Capacity|Hydrogen|Gas|w/o CCS                                                          184
Capacity|Liquids|Biomass|w/ CCS                                                        325
Capacity|Liquids|Biomass|w/o CCS                                                       418
Capacity|Liquids|Oil                                                                   356
Capital Cost|Electricity|Biomass|w/ CCS                                               1601
Capital Cost|Electricity|Biomass|w/o CCS                                              1707
Capital Cost|Electricity|Coal|w/ CCS                                                  1450
Capital Cost|Electricity|Coal|w/o CCS                                                 1664
Capital Cost|Electricity|Gas|w/ CCS                                                   1664
Capital Cost|Electricity|Gas|w/o CCS                                                  1703
Capital Cost|Electricity|Geothermal                                                    945
Capital Cost|Electricity|Hydro                                                        1622
Capital Cost|Electricity|Nuclear                                                      1723
Capital Cost|Electricity|Solar|CSP                                                     730
Capital Cost|Electricity|Solar|PV                                                     1792
Capital Cost|Electricity|Wind|Offshore                                                1238
Capital Cost|Electricity|Wind|Onshore                                                 1344
Capital Cost|Hydrogen|Biomass|w/ CCS                                                   186
Capital Cost|Hydrogen|Biomass|w/o CCS                                                  184
Capital Cost|Hydrogen|Coal|w/ CCS                                                      184
Capital Cost|Hydrogen|Coal|w/o CCS                                                     184
Capital Cost|Hydrogen|Electricity                                                      193
Capital Cost|Hydrogen|Gas|w/ CCS                                                       184
Capital Cost|Liquids|Biomass|w/ CCS                                                    325
Capital Cost|Liquids|Biomass|w/o CCS                                                   358
Capital Cost|Liquids|Coal|w/o CCS                                                      290
Capital Cost|Liquids|Oil                                                               646
Capital Stock                                                                          652
Carbon Sequestration|CCS                                                              3789
Carbon Sequestration|CCS|Biomass                                                      2919
Carbon Sequestration|CCS|Biomass|Energy                                                434
Carbon Sequestration|CCS|Biomass|Energy|Demand|Industry                                293
Carbon Sequestration|CCS|Biomass|Energy|Supply                                        1787
Carbon Sequestration|CCS|Biomass|Energy|Supply|Electricity                            1770
Carbon Sequestration|CCS|Biomass|Energy|Supply|Gases                                   713
Carbon Sequestration|CCS|Biomass|Energy|Supply|Hydrogen                                305
Carbon Sequestration|CCS|Biomass|Energy|Supply|Liquids                                1587
Carbon Sequestration|CCS|Biomass|Energy|Supply|Other                                   197
Carbon Sequestration|CCS|Fossil                                                       3744
Carbon Sequestration|CCS|Fossil|Energy                                                 434
Carbon Sequestration|CCS|Fossil|Energy|Demand|Industry                                 768
Carbon Sequestration|CCS|Fossil|Energy|Supply                                         2553
Carbon Sequestration|CCS|Fossil|Energy|Supply|Electricity                             2464
Carbon Sequestration|CCS|Fossil|Energy|Supply|Gases                                    891
Carbon Sequestration|CCS|Fossil|Energy|Supply|Hydrogen                                 293
Carbon Sequestration|CCS|Fossil|Energy|Supply|Liquids                                 1210
Carbon Sequestration|CCS|Fossil|Energy|Supply|Other                                    211
Carbon Sequestration|CCS|Fossil|Industrial Processes                                    14
Carbon Sequestration|CCS|Industrial Processes                                         1554
Carbon Sequestration|Direct Air Capture                                                926
Carbon Sequestration|Enhanced Weathering                                                 7
Carbon Sequestration|Land Use                                                          982
Carbon Sequestration|Land Use|Afforestation                                            251
Carbon Sequestration|Land Use|Biochar                                                    7
Carbon Sequestration|Land Use|Soil Carbon Management                                     7
Carbon Sequestration|Other                                                            1410
Concentration|CH4                                                                        7
Concentration|CO2                                                                        7
Concentration|N2O                                                                        7
Consumption                                                                           1752
Cumulative Capacity|Electricity|Biomass                                                973
Cumulative Capacity|Electricity|Biomass|w/ CCS                                        1932
Cumulative Capacity|Electricity|Biomass|w/o CCS                                       2084
Cumulative Capacity|Electricity|Coal                                                   953
Cumulative Capacity|Electricity|Coal|w/ CCS                                           1853
Cumulative Capacity|Electricity|Coal|w/o CCS                                          2061
Cumulative Capacity|Electricity|Gas                                                    965
Cumulative Capacity|Electricity|Gas|w/ CCS                                            1930
Cumulative Capacity|Electricity|Gas|w/o CCS                                           2081
Cumulative Capacity|Electricity|Geothermal                                            1596
Cumulative Capacity|Electricity|Hydro                                                 2080
Cumulative Capacity|Electricity|Nuclear                                               2004
Cumulative Capacity|Electricity|Oil                                                    965
Cumulative Capacity|Electricity|Oil|w/ CCS                                            1206
Cumulative Capacity|Electricity|Oil|w/o CCS                                           2031
Cumulative Capacity|Electricity|Solar                                                  967
Cumulative Capacity|Electricity|Solar|CSP                                              916
Cumulative Capacity|Electricity|Solar|PV                                              2087
Cumulative Capacity|Electricity|Wind                                                   972
Cumulative Capacity|Electricity|Wind|Offshore                                         1643
Cumulative Capacity|Electricity|Wind|Onshore                                          2084
Cumulative Capacity|Hydrogen|Biomass                                                   225
Cumulative Capacity|Hydrogen|Biomass|w/ CCS                                            184
Cumulative Capacity|Hydrogen|Biomass|w/o CCS                                           225
Cumulative Capacity|Hydrogen|Coal                                                      184
Cumulative Capacity|Hydrogen|Coal|w/ CCS                                               184
Cumulative Capacity|Hydrogen|Coal|w/o CCS                                              184
Cumulative Capacity|Hydrogen|Electricity                                               272
Cumulative Capacity|Hydrogen|Gas                                                       184
Cumulative Capacity|Hydrogen|Gas|w/ CCS                                                184
Cumulative Capacity|Hydrogen|Gas|w/o CCS                                               184
Cumulative Capacity|Liquids|Biomass|w/o CCS                                             62
Debt|Public                                                                              3
Discount rate|Economy                                                                   10
Discount rate|Residential and Commercial                                                10
Efficiency|Electricity|Biomass|w/ CCS                                                  920
Efficiency|Electricity|Biomass|w/o CCS                                                 782
Efficiency|Electricity|Coal|w/ CCS                                                     932
Efficiency|Electricity|Coal|w/o CCS                                                    782
Efficiency|Electricity|Gas|w/ CCS                                                      930
Efficiency|Electricity|Gas|w/o CCS                                                     781
Efficiency|Liquids|Biomass|w/ CCS                                                      325
Efficiency|Liquids|Biomass|w/o CCS                                                     356
Efficiency|Liquids|Coal|w/o CCS                                                        288
Efficiency|Liquids|Oil                                                                 288
Emissions|BC                                                                           714
Emissions|BC|AFOLU                                                                     669
Emissions|BC|Energy                                                                    669
Emissions|BC|Energy|Demand|Industry                                                    669
Emissions|BC|Energy|Demand|Residential and Commercial                                  156
Emissions|BC|Energy|Demand|Transportation                                              741
Emissions|BC|Energy|Demand|Transportation|Freight                                       72
Emissions|BC|Energy|Demand|Transportation|Passenger                                     72
Emissions|BC|Energy|Supply                                                             669
Emissions|BC|Other                                                                       4
Emissions|C2F6                                                                         901
Emissions|CF4                                                                           84
Emissions|CH4                                                                         3265
Emissions|CH4|AFOLU                                                                   2411
Emissions|CH4|AFOLU|Agriculture                                                        617
Emissions|CH4|AFOLU|Agriculture|Livestock                                              358
Emissions|CH4|AFOLU|Agriculture|Livestock|Enteric Fermentation                         120
Emissions|CH4|AFOLU|Agriculture|Livestock|Manure Management                            358
Emissions|CH4|AFOLU|Agriculture|Rice                                                   120
Emissions|CH4|Energy                                                                  2480
Emissions|CH4|Energy|Demand|Industry                                                   695
Emissions|CH4|Energy|Demand|Residential and Commercial                                 366
Emissions|CH4|Energy|Demand|Transportation                                             695
Emissions|CH4|Energy|Supply                                                            694
Emissions|CH4|Industrial Processes                                                      72
Emissions|CH4|Other                                                                   1011
Emissions|CH4|Waste                                                                     72
Emissions|CO                                                                          1672
Emissions|CO2                                                                         3583
Emissions|CO2|AFOLU                                                                   3124
Emissions|CO2|Energy                                                                  6294
Emissions|CO2|Energy and Industrial Processes                                         3741
Emissions|CO2|Energy|Demand                                                           6181
Emissions|CO2|Energy|Demand|AFOFI                                                     1633
Emissions|CO2|Energy|Demand|Commercial                                                 146
Emissions|CO2|Energy|Demand|Industry                                                  6123
Emissions|CO2|Energy|Demand|Other Sector                                               675
Emissions|CO2|Energy|Demand|Residential                                                146

In [29]:
# Dictionary mapping region codes to full country names
region_to_country = {
    "JPN": "Japan",
    "CHN": "China",
    "BRA": "Brazil",
    "IND": "India",
    "USA": "United States",
    "CAN": "Canada",
    "RUS": "Russia",
    "EU": "European Union",
    "KOR": "South Korea",
    "ZAF": "South Africa",
    "IDN": "Indonesia",
    "MEX": "Mexico",
    "ARG": "Argentina",
    "TUR": "Turkey",
    "THA": "Thailand",
    "VNM": "Vietnam",
    "AUS": "Australia",
    "COL": "Colombia",
    "SAU": "Saudi Arabia",
    "PAK": "Pakistan",
    "TWN": "Taiwan",
    "GBR": "United Kingdom",
    "DEU": "Germany",
    "FRA": "France",
    "SWE": "Sweden",
    "ESP": "Spain",
    "POL": "Poland",
    "GRC": "Greece",
    "CZE": "Czech Republic",
    "FIN": "Finland",
    "ITA": "Italy",
    "CHE": "Switzerland",
    "NGA": "Nigeria",
    "PER": "Peru",
    "NZL": "New Zealand",
    "BGD": "Bangladesh",
    "MOZ": "Mozambique",
    "EGY": "Egypt",
    "ETH": "Ethiopia",
    "KEN": "Kenya",
    "VEN": "Venezuela",
    "BGR": "Bulgaria",
    "HUN": "Hungary",
    "NLD": "Netherlands",
    "IRL": "Ireland",
    "DNK": "Denmark",
    "PRT": "Portugal",
    "BEL": "Belgium",
    "AUT": "Austria",
    "NOR": "Norway",
    "LUX": "Luxembourg",
    "MYS": "Malaysia",
    "ECU": "Ecuador",
    "MLT": "Malta",
    "CYP": "Cyprus",
    "ISL": "Iceland",
    "UGA": "Uganda",
    "BOL": "Bolivia",
    "CHL": "Chile",
    "ETH": "Ethiopia",
    "GHA": "Ghana",
    "KEN": "Kenya",
    "VEN": "Venezuela",
    "ROU": "Romania",
    "HUN": "Hungary",
    "NLD": "Netherlands",
    "SVN": "Slovenia",
    "IRL": "Ireland",
    "DNK": "Denmark",
    "PRT": "Portugal",
    "BEL": "Belgium",
    "SVK": "Slovakia",
    "BGR": "Bulgaria",
    "HRV": "Croatia",
    "LTU": "Lithuania",
    "AUT": "Austria",
    "LVA": "Latvia",
    "NOR": "Norway",
    "EST": "Estonia",
    "LUX": "Luxembourg",
    "MYS": "Malaysia",
    "ECU": "Ecuador",
    "MLT": "Malta",
    "CYP": "Cyprus",
    "ISL": "Iceland",
    "NIC": "Nicaragua",
    "PNG": "Papua New Guinea",
    "NPL": "Nepal",
    "OMN": "Oman",
    "PAN": "Panama",
    "PHL": "Philippines",
    "PSE": "Palestine",
    "PRI": "Puerto Rico",
    "PRK": "North Korea",
    "PRY": "Paraguay",
    "PYF": "French Polynesia",
    "QAT": "Qatar",
    "NCL": "New Caledonia",
    "NER": "Niger",
    "MKD": "North Macedonia",
    "NAM": "Namibia",
    "MYT": "Mayotte",
    "MWI": "Malawi",
    "MUS": "Mauritius",
    "MTQ": "Martinique",
    "MRT": "Mauritania",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MMR": "Myanmar",
    "MLI": "Mali",
    "MDV": "Maldives",
    "MDG": "Madagascar",
    "MDA": "Moldova",
    "MAR": "Morocco",
    "MAC": "Macau",
    "REU": "Réunion",
    "SUR": "Suriname",
    "RWA": "Rwanda",
    "TLS": "Timor-Leste",
    "LKA": "Sri Lanka",
    "ZMB": "Zambia",
    "YEM": "Yemen",
    "WSM": "Samoa",
    "VUT": "Vanuatu",
    "VIR": "U.S. Virgin Islands",
    "VCT": "Saint Vincent and the Grenadines",
    "UZB": "Uzbekistan",
    "URY": "Uruguay",
    "UKR": "Ukraine",
    "TZA": "Tanzania",
    "TUN": "Tunisia",
    "TTO": "Trinidad and Tobago",
    "TON": "Tonga",
    "TKM": "Turkmenistan",
    "SDN": "Sudan",
    "TJK": "Tajikistan",
    "TGO": "Togo",
    "TCD": "Chad",
    "SYR": "Syria",
    "SYC": "Seychelles",
    "SWZ": "Eswatini",
    "STP": "São Tomé and Príncipe",
    "SRB": "Serbia",
    "SOM": "Somalia",
    "SLV": "El Salvador",
    "SLE": "Sierra Leone",
    "SLB": "Solomon Islands",
    "SGP": "Singapore",
    "SEN": "Senegal",
    "LSO": "Lesotho",
    "ERI": "Eritrea",
    "LCA": "Saint Lucia",
    "BLZ": "Belize",
    "DJI": "Djibouti",
    "CUB": "Cuba",
    "CRI": "Costa Rica",
    "CPV": "Cabo Verde",
    "COM": "Comoros",
    "COG": "Congo",
    "COD": "Democratic Republic of the Congo",
    "CMR": "Cameroon",
    "CIV": "Côte d'Ivoire",
    "CAF": "Central African Republic",
    "BWA": "Botswana",
    "BTN": "Bhutan",
    "BRN": "Brunei",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "LBY": "Libya",
    "BIH": "Bosnia and Herzegovina",
    "BHS": "Bahamas",
    "BHR": "Bahrain",
    "BFA": "Burkina Faso",
    "BEN": "Benin",
    "BDI": "Burundi",
    "AZE": "Azerbaijan",
    "ATG": "Antigua and Barbuda",
    "ARM": "Armenia",
    "ARE": "United Arab Emirates",
    "ALB": "Albania",
    "AGO": "Angola",
    "AFG": "Afghanistan",
    "ABW": "Aruba",
    "DOM": "Dominican Republic",
    "DZA": "Algeria",
    "ESH": "Western Sahara",
    "FJI": "Fiji",
    "LBR": "Liberia",
    "LBN": "Lebanon",
    "LAO": "Laos",
    "KWT": "Kuwait",
    "KIR": "Kiribati",
    "KHM": "Cambodia",
    "KGZ": "Kyrgyzstan",
    "KAZ": "Kazakhstan",
    "JOR": "Jordan",
    "JAM": "Jamaica",
    "ISR": "Israel",
    "IRQ": "Iraq",
    "IRN": "Iran",
    "HTI": "Haiti",
    "HND": "Honduras",
    "HKG": "Hong Kong",
    "GUY": "Guyana",
    "GUM": "Guam",
    "GUF": "French Guiana",
    "GTM": "Guatemala",
    "GRD": "Grenada",
    "GNQ": "Equatorial Guinea",
    "GNB": "Guinea-Bissau",
    "GMB": "Gambia",
    "GLP": "Guadeloupe",
    "GIN": "Guinea",
    "GEO": "Georgia",
    "GAB": "Gabon",
    "FSM": "Micronesia",
    "ZWE": "Zimbabwe"
}

# Map the region codes to full country names
master['Country'] = master['Region'].map(region_to_country)

master.head()

,Model,Scenario,Region,Variable,Unit,1990,1995,2000,2005,2007,2008,2010,2011,2012,2013,2014,2015,2018,2020,2021,2022,2023,2024,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100,2110,2130,2150,Country
0,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Carbon Sequestration|CCS|Fossil,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
1,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Consumption,billion US$2010/yr,NaN,NaN,NaN,NaN,NaN,NaN,1938.938790,NaN,NaN,NaN,NaN,2050.443979,NaN,2283.981465,NaN,NaN,NaN,NaN,2589.256395,2919.127020,3254.001592,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
2,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,473.103455,NaN,NaN,NaN,NaN,446.043213,NaN,416.863159,NaN,NaN,NaN,NaN,396.592651,412.047394,433.487579,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
3,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,321.993973,NaN,NaN,NaN,NaN,307.740860,NaN,309.829834,NaN,NaN,NaN,NaN,319.038116,331.080795,344.977493,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
4,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Commercial,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,19.644783,NaN,NaN,NaN,NaN,20.231993,NaN,22.672163,NaN,NaN,NaN,NaN,25.879625,29.244556,32.631683,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom

In [30]:
master_filtered = master.copy()

regions_over_2000 = ['JPN', 'CHN', 'BRA', 'IND', 'USA', 'CAN', 'RUS', 'EU', 'KOR', 'ZAF', 'IDN', 'MEX', 'ARG', 'TUR', 'THA', 'VNM', 'AUS', 'COL', 'SAU', 'PAK', 'TWN', 'GBR']

master_filtered = master_filtered[master_filtered['Region'].isin(regions_over_2000)]

master_filtered.shape

(989937, 43)

In [31]:
# Filter rows where 'Variable' contains 'Emissions' or 'Sequestration'
master_filtered = master_filtered[
    master_filtered['Variable'].str.contains('Emissions|Sequestration', case=False, na=False)
]

# Check the shape of the filtered DataFrame
master_filtered.shape

(189301, 43)

In [32]:
master_filtered['Variable'].unique()

array(['Carbon Sequestration|CCS|Fossil', 'Emissions|CO2|Energy',
       'Emissions|CO2|Energy|Demand',
       'Emissions|CO2|Energy|Demand|Commercial',
       'Emissions|CO2|Energy|Demand|Industry',
       'Emissions|CO2|Energy|Demand|Residential',
       'Emissions|CO2|Energy|Demand|Residential and Commercial',
       'Emissions|CO2|Energy|Demand|Transportation',
       'Emissions|CO2|Energy|Demand|Transportation|Road',
       'Emissions|CO2|Energy|Supply', 'Carbon Sequestration|CCS',
       'Carbon Sequestration|CCS|Biomass',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Electricity',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Liquids',
       'Carbon Sequestration|CCS|Fossil|Energy|Demand|Industry',
       'Carbon Sequestration|CCS|Fossil|Energy|Supply',
       'Carbon Sequestration|CCS|Fossil|Energy|Supply|Electricity',
       'Carbon Sequestration|CCS|Fossil|Energy|Supply|Liquids',
       'Carbon Sequestration|CCS|Industrial Processes',
       'Carbon Sequestration|Land Use|Afforestation', 'Emissions|BC',
       'Emissions|BC|AFOLU', 'Emissions|BC|Energy',
       'Emissions|BC|Energy|Demand|Industry',
       'Emissions|BC|Energy|Demand|Transportation',
       'Emissions|BC|Energy|Supply', 'Emissions|CH4',
       'Emissions|CH4|AFOLU', 'Emissions|CH4|AFOLU|Agriculture',
       'Emissions|CH4|AFOLU|Agriculture|Livestock',
       'Emissions|CH4|AFOLU|Agriculture|Livestock|Manure Management',
       'Emissions|CH4|Energy', 'Emissions|CH4|Energy|Demand|Industry',
       'Emissions|CH4|Energy|Demand|Transportation',
       'Emissions|CH4|Energy|Supply', 'Emissions|CO', 'Emissions|CO2',
       'Emissions|CO2|AFOLU',
       'Emissions|CO2|Energy and Industrial Processes',
       'Emissions|CO2|Energy|Demand|AFOFI',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential',
       'Emissions|CO2|Energy|Supply|Electricity',
       'Emissions|CO2|Industrial Processes', 'Emissions|CO|AFOLU',
       'Emissions|CO|Energy', 'Emissions|CO|Energy|Demand|Industry',
       'Emissions|CO|Energy|Demand|Transportation',
       'Emissions|CO|Energy|Supply', 'Emissions|F-Gases', 'Emissions|HFC',
       'Emissions|HFC|HFC125', 'Emissions|HFC|HFC134a',
       'Emissions|HFC|HFC143a', 'Emissions|HFC|HFC227ea',
       'Emissions|HFC|HFC245fa', 'Emissions|HFC|HFC32',
       'Emissions|Kyoto Gases', 'Emissions|N2O', 'Emissions|N2O|AFOLU',
       'Emissions|N2O|AFOLU|Agriculture',
       'Emissions|N2O|AFOLU|Agriculture|Livestock|Manure Management',
       'Emissions|N2O|AFOLU|Agriculture|Managed Soils',
       'Emissions|N2O|Energy', 'Emissions|NH3', 'Emissions|NH3|AFOLU',
       'Emissions|NH3|Energy', 'Emissions|NH3|Energy|Demand|Industry',
       'Emissions|NH3|Energy|Demand|Transportation',
       'Emissions|NH3|Energy|Supply', 'Emissions|NOx',
       'Emissions|NOx|AFOLU', 'Emissions|NOx|Energy',
       'Emissions|NOx|Energy|Demand|Industry',
       'Emissions|NOx|Energy|Demand|Transportation',
       'Emissions|NOx|Energy|Supply', 'Emissions|OC',
       'Emissions|OC|AFOLU', 'Emissions|OC|Energy',
       'Emissions|OC|Energy|Demand|Industry',
       'Emissions|OC|Energy|Demand|Transportation',
       'Emissions|OC|Energy|Supply', 'Emissions|PFC', 'Emissions|SF6',
       'Emissions|Sulfur', 'Emissions|Sulfur|AFOLU',
       'Emissions|Sulfur|Energy',
       'Emissions|Sulfur|Energy|Demand|Industry',
       'Emissions|Sulfur|Energy|Demand|Transportation',
       'Emissions|Sulfur|Energy|Supply', 'Emissions|VOC',
       'Emissions|VOC|AFOLU', 'Emissions|VOC|Energy',
       'Emissions|VOC|Energy|Demand|Industry',
       'Emissions|VOC|Energy|Demand|Transportation',
       'Emissions|VOC|Energy|Supply', 'Emissions|HFC|HFC23',
       'Emissions|HFC|HFC43-10',
       'Emissions|BC|Energy|Demand|Residential and Commercial',
       'Emissions|CH4|Energy|Demand|Residential and Commercial',
       'Emissions|CO|Energy|Demand|Residential and Commercial',
       'Emissions|NH3|Energy|Demand|Residential and Commercial',
       'Emissions|NOx|Energy|Demand|Residential and Commercial',
       'Emissions|OC|Energy|Demand|Residential and Commercial',
       'Emissions|PFC|C2F6', 'Emissions|PFC|CF4',
       'Emissions|Sulfur|Energy|Demand|Residential and Commercial',
       'Emissions|VOC|Energy|Demand|Residential and Commercial',
       'Emissions|CO2|Energy|Supply|Other Sector', 'Emissions|CH4|Other',
       'Emissions|CO2|Other', 'Emissions|N2O|Other',
       'Carbon Sequestration|CCS|Biomass|Energy|Demand|Industry',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Gases',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Hydrogen',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Other',
       'Carbon Sequestration|CCS|Fossil|Energy|Supply|Gases',
       'Carbon Sequestration|CCS|Fossil|Energy|Supply|Hydrogen',
       'Carbon Sequestration|CCS|Fossil|Energy|Supply|Other',
       'Carbon Sequestration|Direct Air Capture',
       'Carbon Sequestration|Enhanced Weathering',
       'Carbon Sequestration|Land Use',
       'Carbon Sequestration|Land Use|Biochar',
       'Carbon Sequestration|Land Use|Soil Carbon Management',
       'Carbon Sequestration|Other',
       'Emissions|CO2|Energy|Demand|Other Sector',
       'Emissions|CO2|Energy|Demand|Transportation|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Passenger',
       'Emissions|CO2|Energy|Supply|Gases',
       'Emissions|CO2|Energy|Supply|Heat',
       'Emissions|CO2|Energy|Supply|Liquids',
       'Emissions|CO2|Energy|Supply|Solids', 'Emissions|PFC|C6F14',
       'Emissions|CH4|AFOLU|Agriculture|Livestock|Enteric Fermentation',
       'Emissions|CH4|AFOLU|Agriculture|Rice',
       'Emissions|BC|Energy|Demand|Transportation|Freight',
       'Emissions|BC|Energy|Demand|Transportation|Passenger',
       'Emissions|CO2|Energy|Demand|Transportation|Aviation',
       'Emissions|CO2|Energy|Demand|Transportation|Aviation|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Aviation|Passenger',
       'Emissions|CO2|Energy|Demand|Transportation|Maritime',
       'Emissions|CO2|Energy|Demand|Transportation|Maritime|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Rail',
       'Emissions|CO2|Energy|Demand|Transportation|Rail|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Rail|Passenger',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|2W&3W',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|Bus',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|LDV',
       'Emissions|CO|Energy|Demand|Transportation|Freight',
       'Emissions|CO|Energy|Demand|Transportation|Passenger',
       'Emissions|OC|Energy|Demand|Transportation|Freight',
       'Emissions|OC|Energy|Demand|Transportation|Passenger',
       'Emissions|Sulfur|Energy|Demand|Transportation|Freight',
       'Emissions|Sulfur|Energy|Demand|Transportation|Passenger',
       'Emissions|VOC|Energy|Demand|Transportation|Freight',
       'Emissions|VOC|Energy|Demand|Transportation|Passenger',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating|Cooking',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating|Water',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Education',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Health',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Heating|Space',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Heating|Water',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Hotels',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Offices',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating|Space',
       'Carbon Sequestration|CCS|Biomass|Energy',
       'Carbon Sequestration|CCS|Fossil|Energy',
       'Carbon Sequestration|CCS|Fossil|Industrial Processes',
       'Emissions|C2F6', 'Emissions|CF4', 'Emissions|BC|Other',
       'Emissions|CO|Other', 'Emissions|NH3|Other', 'Emissions|NOx|Other',
       'Emissions|OC|Other', 'Emissions|Sulfur|Other',
       'Emissions|VOC|Other', 'Emissions|CH4|Industrial Processes',
       'Emissions|CH4|Waste', 'Emissions|CO2|Waste',
       'Emissions|HFC|Industrial Processes',
       'Emissions|N2O|Industrial Processes', 'Emissions|N2O|Waste',
       'Trade|Emissions Allowances|Value',
       'Trade|Emissions Allowances|Volume'], dtype=object)

In [33]:
# List of specific values to drop
values_to_drop = ['Emissions|BC', 'Emissions|BC|AFOLU', 'Emissions|BC|Energy', 'Emissions|BC|Energy|Demand|Industry', 'Emissions|BC|Energy|Demand|Transportation', 'Emissions|BC|Energy|Supply', 
                  'Emissions|CO', 'Emissions|CO|AFOLU', 'Emissions|CO|Energy', 'Emissions|CO|Energy|Demand|Industry', 'Emissions|CO|Energy|Demand|Transportation', 'Emissions|CO|Energy|Supply', 
                  'Emissions|F-Gases', 'Emissions|HFC', 'Emissions|HFC|HFC125', 'Emissions|HFC|HFC134a', 'Emissions|HFC|HFC143a', 'Emissions|HFC|HFC227ea', 'Emissions|HFC|HFC245fa', 
                  'Emissions|HFC|HFC32', 'Emissions|Kyoto Gases', 'Emissions|NH3', 'Emissions|NH3|AFOLU', 'Emissions|NH3|Energy', 'Emissions|NH3|Energy|Demand|Industry', 
                  'Emissions|NH3|Energy|Demand|Transportation', 'Emissions|NH3|Energy|Supply', 'Emissions|NOx', 'Emissions|NOx|AFOLU', 'Emissions|NOx|Energy', 'Emissions|NOx|Energy|Demand|Industry', 
                  'Emissions|NOx|Energy|Demand|Transportation', 'Emissions|NOx|Energy|Supply', 'Emissions|OC', 'Emissions|OC|AFOLU', 'Emissions|OC|Energy', 'Emissions|OC|Energy|Demand|Industry', 
                  'Emissions|OC|Energy|Demand|Transportation', 'Emissions|OC|Energy|Supply', 'Emissions|PFC', 'Emissions|SF6', 'Emissions|Sulfur', 'Emissions|Sulfur|AFOLU', 'Emissions|Sulfur|Energy', 
                  'Emissions|Sulfur|Energy|Demand|Industry', 'Emissions|Sulfur|Energy|Demand|Transportation', 'Emissions|Sulfur|Energy|Supply', 'Emissions|VOC', 'Emissions|VOC|AFOLU', 'Emissions|VOC|Energy', 
                  'Emissions|VOC|Energy|Demand|Industry', 'Emissions|VOC|Energy|Demand|Transportation', 'Emissions|VOC|Energy|Supply', 'Emissions|HFC|HFC23', 'Emissions|HFC|HFC43-10', 
                  'Emissions|BC|Energy|Demand|Residential and Commercial', 'Emissions|CO|Energy|Demand|Residential and Commercial', 'Emissions|NH3|Energy|Demand|Residential and Commercial', 
                  'Emissions|NOx|Energy|Demand|Residential and Commercial', 'Emissions|OC|Energy|Demand|Residential and Commercial', 'Emissions|PFC|C2F6', 'Emissions|PFC|CF4', 
                  'Emissions|Sulfur|Energy|Demand|Residential and Commercial', 'Emissions|VOC|Energy|Demand|Residential and Commercial', 'Emissions|PFC|C6F14', 'Emissions|BC|Energy|Demand|Transportation|Freight', 
                  'Emissions|BC|Energy|Demand|Transportation|Passenger', 'Emissions|CO|Energy|Demand|Transportation|Freight', 'Emissions|CO|Energy|Demand|Transportation|Passenger', 
                  'Emissions|OC|Energy|Demand|Transportation|Freight', 'Emissions|OC|Energy|Demand|Transportation|Passenger', 'Emissions|Sulfur|Energy|Demand|Transportation|Freight', 
                  'Emissions|Sulfur|Energy|Demand|Transportation|Passenger', 'Emissions|VOC|Energy|Demand|Transportation|Freight', 'Emissions|VOC|Energy|Demand|Transportation|Passenger', 'Emissions|C2F6', 
                  'Emissions|CF4', 'Emissions|BC|Other', 'Emissions|CO|Other', 'Emissions|NH3|Other', 'Emissions|NOx|Other', 'Emissions|OC|Other', 'Emissions|Sulfur|Other', 'Emissions|VOC|Other', 
                  'Emissions|HFC|Industrial Processes', 'Trade|Emissions Allowances|Value', 'Trade|Emissions Allowances|Volume', 'Carbon Sequestration|CCS', 'Carbon Sequestration|CCS|Fossil', 
                  'Emissions|CO2', 'Emissions|N2O', 'Emissions|CH4', 'Carbon Sequestration|CCS|Fossil|Energy|Supply', 'Carbon Sequestration|CCS|Fossil|Energy|Supply|Electricity', 'Emissions|CO2|Energy', 
                  'Emissions|N2O|Energy', 'Emissions|CH4|Energy', 'Carbon Sequestration|CCS|Industrial Processes', 'Carbon Sequestration|Other', 'Carbon Sequestration|CCS|Fossil|Energy|Supply|Liquids', 
                  'Emissions|N2O|Other', 'Emissions|CH4|Other', 'Emissions|CO2|Energy|Supply|Other Sector', 'Carbon Sequestration|CCS|Fossil|Energy|Supply|Gases', 'Carbon Sequestration|CCS|Fossil|Energy|Demand|Industry', 
                  'Emissions|CO2|Energy|Demand|Other Sector', 'Carbon Sequestration|CCS|Fossil|Energy', 'Carbon Sequestration|CCS|Fossil|Energy|Supply|Hydrogen', 'Carbon Sequestration|CCS|Fossil|Energy|Supply|Other', 
                  'Emissions|CH4|AFOLU|Agriculture|Livestock|Enteric Fermentation', 'Emissions|CH4|AFOLU|Agriculture|Rice', 'Emissions|CO2|Other', 'Carbon Sequestration|CCS|Fossil|Industrial Processes', 
                  'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating|Water', 'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating|Cooking', 
                  'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating', 'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Education', 
                  'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Health', 'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Heating|Space', 
                  'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Heating|Water', 'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Hotels', 
                  'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial|Offices', 'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential|Heating|Space'] 

# Drop rows where Variable is in the list of values to drop
master_filtered.drop(master_filtered[master_filtered['Variable'].isin(values_to_drop)].index, inplace=True)

# Step 3: Check the shape
print(master_filtered.shape)

(82692, 43)

In [34]:
master_filtered['Variable'].unique()

array(['Emissions|CO2|Energy|Demand',
       'Emissions|CO2|Energy|Demand|Commercial',
       'Emissions|CO2|Energy|Demand|Industry',
       'Emissions|CO2|Energy|Demand|Residential',
       'Emissions|CO2|Energy|Demand|Residential and Commercial',
       'Emissions|CO2|Energy|Demand|Transportation',
       'Emissions|CO2|Energy|Demand|Transportation|Road',
       'Emissions|CO2|Energy|Supply', 'Carbon Sequestration|CCS|Biomass',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Electricity',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Liquids',
       'Carbon Sequestration|Land Use|Afforestation',
       'Emissions|CH4|AFOLU', 'Emissions|CH4|AFOLU|Agriculture',
       'Emissions|CH4|AFOLU|Agriculture|Livestock',
       'Emissions|CH4|AFOLU|Agriculture|Livestock|Manure Management',
       'Emissions|CH4|Energy|Demand|Industry',
       'Emissions|CH4|Energy|Demand|Transportation',
       'Emissions|CH4|Energy|Supply', 'Emissions|CO2|AFOLU',
       'Emissions|CO2|Energy and Industrial Processes',
       'Emissions|CO2|Energy|Demand|AFOFI',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial',
       'Emissions|CO2|Energy|Demand|Residential and Commercial|Residential',
       'Emissions|CO2|Energy|Supply|Electricity',
       'Emissions|CO2|Industrial Processes', 'Emissions|N2O|AFOLU',
       'Emissions|N2O|AFOLU|Agriculture',
       'Emissions|N2O|AFOLU|Agriculture|Livestock|Manure Management',
       'Emissions|N2O|AFOLU|Agriculture|Managed Soils',
       'Emissions|CH4|Energy|Demand|Residential and Commercial',
       'Carbon Sequestration|CCS|Biomass|Energy|Demand|Industry',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Gases',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Hydrogen',
       'Carbon Sequestration|CCS|Biomass|Energy|Supply|Other',
       'Carbon Sequestration|Direct Air Capture',
       'Carbon Sequestration|Enhanced Weathering',
       'Carbon Sequestration|Land Use',
       'Carbon Sequestration|Land Use|Biochar',
       'Carbon Sequestration|Land Use|Soil Carbon Management',
       'Emissions|CO2|Energy|Demand|Transportation|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Passenger',
       'Emissions|CO2|Energy|Supply|Gases',
       'Emissions|CO2|Energy|Supply|Heat',
       'Emissions|CO2|Energy|Supply|Liquids',
       'Emissions|CO2|Energy|Supply|Solids',
       'Emissions|CO2|Energy|Demand|Transportation|Aviation',
       'Emissions|CO2|Energy|Demand|Transportation|Aviation|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Aviation|Passenger',
       'Emissions|CO2|Energy|Demand|Transportation|Maritime',
       'Emissions|CO2|Energy|Demand|Transportation|Maritime|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Rail',
       'Emissions|CO2|Energy|Demand|Transportation|Rail|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Rail|Passenger',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Freight',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|2W&3W',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|Bus',
       'Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|LDV',
       'Carbon Sequestration|CCS|Biomass|Energy',
       'Emissions|CH4|Industrial Processes', 'Emissions|CH4|Waste',
       'Emissions|CO2|Waste', 'Emissions|N2O|Industrial Processes',
       'Emissions|N2O|Waste'], dtype=object)

In [35]:
master_filtered['Variable'].value_counts()

Variable
Emissions|CO2|Energy|Demand|Transportation                            5834
Emissions|CO2|Energy|Supply                                           5817
Emissions|CO2|Energy|Demand                                           5787
Emissions|CO2|Energy|Demand|Industry                                  5718
Emissions|CO2|Energy|Demand|Residential and Commercial                4674
Emissions|CO2|Energy|Supply|Electricity                               3856
Emissions|CO2|Energy and Industrial Processes                         3739
Emissions|CO2|Industrial Processes                                    3252
Emissions|CO2|Energy|Demand|Residential and Commercial|Residential    3136
Emissions|CO2|Energy|Demand|Residential and Commercial|Commercial     3136
Emissions|CO2|AFOLU                                                   3122
Carbon Sequestration|CCS|Biomass                                      2917
Emissions|CO2|Energy|Supply|Liquids                                   2755
Emissions|CO2|Energy|Supply|Gases                                     2755
Emissions|CH4|AFOLU                                                   2409
Emissions|N2O|AFOLU                                                   2409
Emissions|CO2|Energy|Supply|Solids                                    2041
Carbon Sequestration|CCS|Biomass|Energy|Supply                        1787
Carbon Sequestration|CCS|Biomass|Energy|Supply|Electricity            1770
Carbon Sequestration|CCS|Biomass|Energy|Supply|Liquids                1587
Emissions|CO2|Energy|Demand|AFOFI                                     1347
Carbon Sequestration|Land Use                                          980
Carbon Sequestration|Direct Air Capture                                926
Carbon Sequestration|CCS|Biomass|Energy|Supply|Gases                   713
Emissions|CH4|Energy|Demand|Industry                                   695
Emissions|CH4|Energy|Demand|Transportation                             695
Emissions|CH4|Energy|Supply                                            694
Emissions|CH4|AFOLU|Agriculture                                        617
Emissions|N2O|AFOLU|Agriculture                                        617
Emissions|CO2|Energy|Demand|Transportation|Road                        547
Emissions|CO2|Energy|Demand|Transportation|Maritime                    500
Carbon Sequestration|CCS|Biomass|Energy                                434
Emissions|CO2|Energy|Supply|Heat                                       404
Emissions|CH4|Energy|Demand|Residential and Commercial                 366
Emissions|CH4|AFOLU|Agriculture|Livestock                              358
Emissions|N2O|AFOLU|Agriculture|Livestock|Manure Management            358
Emissions|N2O|AFOLU|Agriculture|Managed Soils                          358
Emissions|CH4|AFOLU|Agriculture|Livestock|Manure Management            358
Carbon Sequestration|CCS|Biomass|Energy|Supply|Hydrogen                305
Carbon Sequestration|CCS|Biomass|Energy|Demand|Industry                293
Carbon Sequestration|Land Use|Afforestation                            251
Carbon Sequestration|CCS|Biomass|Energy|Supply|Other                   197
Emissions|CO2|Energy|Demand|Transportation|Freight                     190
Emissions|CO2|Energy|Demand|Transportation|Passenger                   190
Emissions|CO2|Energy|Demand|Commercial                                 146
Emissions|CO2|Energy|Demand|Residential                                146
Emissions|CO2|Energy|Demand|Transportation|Road|Freight                116
Emissions|CO2|Energy|Demand|Transportation|Road|Passenger              116
Emissions|CO2|Energy|Demand|Transportation|Rail                        113
Emissions|CO2|Energy|Demand|Transportation|Rail|Freight                106
Emissions|CO2|Energy|Demand|Transportation|Rail|Passenger              106
Emissions|CO2|Energy|Demand|Transportation|Aviation                     91
Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|2W&3W         85
Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|Bus           85
Emissions|CO2|Energy|Demand|Transportation|Road|Passenger|LDV           85
Emissions|CO2|Energy|Demand|Transportation|Aviation|Passenger           84
Emissions|CO2|Energy|Demand|Transportation|Maritime|Freight             73
Emissions|CH4|Industrial Processes                                      72
Emissions|CH4|Waste                                                     72
Emissions|CO2|Waste                                                     72
Emissions|N2O|Industrial Processes                                      72
Emissions|N2O|Waste                                                     72
Emissions|CO2|Energy|Demand|Transportation|Aviation|Freight             65
Carbon Sequestration|Land Use|Soil Carbon Management                     7
Carbon Sequestration|Land Use|Biochar                                    7
Carbon Sequestration|Enhanced Weathering                                 7
Name: count, dtype: int64

In [36]:
master_filtered.head()

,Model,Scenario,Region,Variable,Unit,1990,1995,2000,2005,2007,2008,2010,2011,2012,2013,2014,2015,2018,2020,2021,2022,2023,2024,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100,2110,2130,2150,Country
3,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,321.993973,NaN,NaN,NaN,NaN,307.740860,NaN,309.829834,NaN,NaN,NaN,NaN,319.038116,331.080795,344.977493,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
4,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Commercial,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,19.644783,NaN,NaN,NaN,NaN,20.231993,NaN,22.672163,NaN,NaN,NaN,NaN,25.879625,29.244556,32.631683,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
5,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Industry,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,80.992957,NaN,NaN,NaN,NaN,84.178561,NaN,81.970872,NaN,NaN,NaN,NaN,82.967468,84.497656,86.346069,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
6,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Residential,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,78.415421,NaN,NaN,NaN,NaN,63.838432,NaN,62.009739,NaN,NaN,NaN,NaN,61.496624,61.609833,62.016922,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom
7,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Residential and Co...,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,98.060204,NaN,NaN,NaN,NaN,84.070425,NaN,84.681902,NaN,NaN,NaN,NaN,87.376249,90.854389,94.648605,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom

In [37]:
model = master_filtered['Model'].nunique()
scenario = master_filtered['Scenario'].nunique()
region = master_filtered['Region'].nunique()
variable = master_filtered['Variable'].nunique()
unit = master_filtered['Unit'].nunique()

print('Number of Unique Models: ', model)
print('Number of Unique Scenarios: ', scenario)
print('Number of Unique Regions: ', region)
print('Number of Unique Variables: ', variable)
print('Number of Unique Units: ', unit)

Number of Unique Models:  63
Number of Unique Scenarios:  497
Number of Unique Regions:  22
Number of Unique Variables:  66
Number of Unique Units:  3

In [38]:
# Initialize the Species column with NaN
master_filtered['Species'] = np.nan

# Update 'Species' with characters at positions 11, 12, and 13 for rows starting with 'E'
master_filtered.loc[
    master_filtered['Variable'].str.startswith('E', na=False),  # Condition: starts with 'E'
    'Species'
] = master_filtered['Variable'].str[10:13]  # Extract 11th, 12th, and 13th characters

master_filtered.head()

/var/folders/vc/zqm44p0x6dx4m48jclbr5q280000gn/T/ipykernel_46239/88191619.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['CO2' 'CO2' 'CO2' ... 'N2O' 'N2O' 'N2O']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  master_filtered.loc[

,Model,Scenario,Region,Variable,Unit,1990,1995,2000,2005,2007,2008,2010,2011,2012,2013,2014,2015,2018,2020,2021,2022,2023,2024,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100,2110,2130,2150,Country,Species
3,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,321.993973,NaN,NaN,NaN,NaN,307.740860,NaN,309.829834,NaN,NaN,NaN,NaN,319.038116,331.080795,344.977493,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom,CO2
4,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Commercial,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,19.644783,NaN,NaN,NaN,NaN,20.231993,NaN,22.672163,NaN,NaN,NaN,NaN,25.879625,29.244556,32.631683,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom,CO2
5,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Industry,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,80.992957,NaN,NaN,NaN,NaN,84.178561,NaN,81.970872,NaN,NaN,NaN,NaN,82.967468,84.497656,86.346069,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom,CO2
6,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Residential,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,78.415421,NaN,NaN,NaN,NaN,63.838432,NaN,62.009739,NaN,NaN,NaN,NaN,61.496624,61.609833,62.016922,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom,CO2
7,7see Mk5-20 GB,JPC to 0.8 of asymptote,GBR,Emissions|CO2|Energy|Demand|Residential and Co...,Mt CO2/yr,NaN,NaN,NaN,NaN,NaN,NaN,98.060204,NaN,NaN,NaN,NaN,84.070425,NaN,84.681902,NaN,NaN,NaN,NaN,87.376249,90.854389,94.648605,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United Kingdom,CO2

In [39]:
group_column = 'Region'

# Save each region as a separate CSV file
for value, group_df in master_filtered.groupby(group_column):
    filename = f'{value}_data.csv'  # Define the filename dynamically
    group_df.to_csv(filename, index=False)  # Save the group as a CSV file
    print(f"Saved {filename}")

Saved ARG_data.csv
Saved AUS_data.csv
Saved BRA_data.csv
Saved CAN_data.csv
Saved CHN_data.csv
Saved COL_data.csv
Saved EU_data.csv
Saved GBR_data.csv
Saved IDN_data.csv
Saved IND_data.csv
Saved JPN_data.csv
Saved KOR_data.csv
Saved MEX_data.csv
Saved PAK_data.csv
Saved RUS_data.csv
Saved SAU_data.csv
Saved THA_data.csv
Saved TUR_data.csv
Saved TWN_data.csv
Saved USA_data.csv
Saved VNM_data.csv
Saved ZAF_data.csv